apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "model.name" . }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s
