services:
  model:
    image: voa2000/hpp-model:latest 
    build:
      context: .
      dockerfile: model_app/src/api/Dockerfile
    ports:
      - "8008:8000"
    container_name: model-app
    networks:
      - house-price-network

  streamlit:
    image: voa2000/hpp-streamlit:latest
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    container_name: streamlit-app
    environment:
      API_URL: http://model:8000
    depends_on:
      - model
    networks:
      - house-price-network

networks:
  house-price-network:
    name: house-price-network