apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment/kubernetes/deployment.yaml
  - deployment/kubernetes/service.yaml
  - deployment/kubernetes/configmap.yaml
  - deployment/kubernetes/secret.yaml

namespace: house-price-predictor