apiVersion: v1
kind: Service
metadata:
  labels:
    app: model
  name: model
spec:
  selector:
    app: model
  type: NodePort
  ports:
    - name: http # Service port for FastAPI
      nodePort: 30100
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: metrics # Service port for Prometheus metrics
      nodePort: 31100
      port: 9100
      protocol: TCP
      targetPort: 9100
