apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: house-price-api-monitor
  namespace: house-price-predictor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: model
  namespaceSelector:
    matchNames:
      - house-price-predictor
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
