apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamlit
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  strategy: {}
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - image: voa2000/streamlit:v1.0.2
        imagePullPolicy: Always
        name: streamlit
        ports:
        - containerPort: 8501
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
status: {}
