image:
  repository: voa2000/house-price-model
  tag: v1.0.3
  pullPolicy: Always

service:
  port: 8000
  metricsPort: 9100

resources:
  requests:
    cpu: "500m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "512Mi"

autoscaling:
  vpa:
    enabled: true
    name: model
    updateMode: InPlaceOrRecreate
    minAllowed:
      cpu: 50m
      memory: 64Mi
    maxAllowed:
      cpu: 500m
      memory: 512Mi
    controlledResources:
      - cpu
      - memory

  keda:
    enabled: true
    name: fastapi-latency-autoscaler
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 30
    cooldownPeriod: 300
    prometheusServerAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
    latencyMetricName: fastapi_latency_p95
    latencyQuery: |
      histogram_quantile(0.95,
        sum(rate(http_request_duration_seconds_bucket[1m])) by (le))
    latencyThreshold: "0.08"
    requestRateMetricName: request_rate
    requestRateQuery: sum(rate(http_requests_total[1m]))
    requestRateThreshold: "20"
    cpuMetricType: Utilization
    cpuValue: "70"