image:
  repository: voa2000/house-price-model
  tag: v0.0.1-dev.9
  pullPolicy: Always
service:
  port: 8000
  metricsPort: 9100
resources:
  requests:
    cpu: "500m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "512Mi"
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
autoscaling:
  vpa:
    enabled: true
    name: model
    updateMode: InPlaceOrRecreate
    minAllowed:
      cpu: 50m
      memory: 64Mi
    maxAllowed:
      cpu: 500m
      memory: 512Mi
    controlledResources:
      - cpu
      - memory
  