apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streamlit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/viv-capgemini/house-price-predictor.git
    targetRevision: main
    path: gitops/apps/streamlit
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
